---
apiVersion: v1
kind: Pod
metadata:
  name: http-probe-for-liveness-and-readiness
spec:
  containers:
    - name: http-server
      image: httpd:latest
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1