---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
    - name: readiness-probe
      image: ubuntu:latest
      command:
        - /bin/bash
        - -ec
        - sleep 30; touch /tmp/ready; sleep 600
      readinessProbe:
        exec:
          command: 
            - cat
            - /tmp/ready
          initialDelaySeconds: 5
          periodSeconds: 5